<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Inicio</title>
  </head>
  <body>
    <h1 align="center">Seleccione una zona</h1>


    <!-- Image Map Generated by http://www.image-map.net/ -->
  <div class="imagen" align="center"><img src="mapadistritos2.gif" alt="Mapa Distritos" usemap="#image-map">

<map name="image-map">
    <area target="" alt="" title="moncloa" href="Intermedio.php?destino=Salamanca" coords="125,81,134,79,142,73,148,62,150,52,154,41,162,40,170,43,179,45,188,40,198,36,207,30,215,25,222,20,227,27,229,38,230,48,230,59,225,66,225,76,224,84,224,93,224,100,224,108,220,115,219,124,222,129,216,129,209,129,200,129,189,127,181,124,169,121,159,116,150,110,143,104,133,98,126,92" shape="poly">
    <area target="" alt="" title="salamanca" href="Intermedio.php?destino=Moncloa" coords="56,51,62,54,71,57,78,58,86,61,92,67,100,70,109,73,118,78,123,84,127,92,130,103,131,113,133,122,133,130,133,140,133,146,133,153,127,157,123,163,119,170,111,173,104,173,95,170,89,166,85,161,79,158,73,159,67,160,61,160,55,160,55,151,50,144,44,138,37,136,33,129,29,124,31,117,35,108,42,104,49,99,55,91,59,81,57,69,56,58" shape="poly">
    <area target="" alt="" title="retiro" href="Intermedio.php?destino=Retiro" coords="131,98,138,101,146,107,154,112,161,117,171,120,180,124,190,127,202,129,211,129,222,129,224,137,225,147,222,155,217,158,210,166,205,172,202,181,198,191,193,196,182,200,178,206,169,201,161,189,156,181,150,174,142,167,136,165,128,165,129,155,135,148,135,134,134,123,132,115,131,106" shape="poly">
    <area target="" alt="" title="arganzuela" href="Intermedio.php?destino=Arganzuela" coords="178,208,174,216,174,224,174,233,167,238,158,245,153,247,146,251,138,256,129,256,121,249,115,242,109,237,103,232,94,221,82,214,73,212,66,209,58,204,48,203,39,197,39,186,40,174,49,169,54,159,67,158,77,155,88,162,97,169,107,172,118,173,124,167,134,166,143,168,152,175,160,187,166,196,173,203" shape="poly">
</map>
</div>
<div class="hiperVin"align="center" >
  <a href="Intermedio.php?destino=Moncloa"><h4 >MONCLOA</h4></a>
  <a href="Intermedio.php?destino=Salamanca"><h4 >SALAMANCA</h4></a>
  <a href="Intermedio.php?destino=Retiro"><h4 >RETIRO</h4></a>
  <h4>ARGANZUELA</h4>
</div>

  </body>
</html>